# Generated by Django 6.1 on 2026-08-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='e.g. Artificial Intelligence, Photography, Finance', max_length=200)),
                ('current_level', models.CharField(choices=[('Complete Beginner', 'Complete Beginner (Brand new to the field)'), ('Beginner', 'Beginner (Basic familiarity / know fundamentals)'), ('Intermediate', 'Intermediate (Hands-on experience, looking to level up)'), ('Advanced', 'Advanced (Deep experience, looking for mastery/specialization)')], default='Beginner', max_length=50)),
                ('goal', models.CharField(help_text='e.g. Become an AI Engineer, Start a Portrait Studio', max_length=300)),
                ('available_time', models.CharField(default='2 hours per day', help_text='e.g. 1 hour per day, 2 hours per day, 10 hours/week', max_length=100)),
                ('duration', models.CharField(default='6 months', help_text='e.g. 3 months, 6 months, 1 year', max_length=100)),
                ('existing_skills', models.TextField(blank=True, default='', help_text='Skills or tools you already know')),
                ('user_name', models.CharField(blank=True, default='Learner', help_text='Your name or nickname', max_length=100)),
                ('greeting_message', models.TextField(blank=True, default='')),
                ('junior_advice', models.TextField(blank=True, default='')),
                ('roadmap_content', models.TextField(blank=True, default='', help_text='Full structured overview / raw backup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Stage 1 — Foundations', max_length=255)),
                ('description', models.TextField(help_text='Overview of this stage')),
                ('why_it_matters', models.TextField(help_text='Why this stage is crucial for the goal')),
                ('what_to_practice', models.TextField(blank=True, default='', help_text='Key drills and hands-on exercises')),
                ('suggested_projects', models.TextField(blank=True, default='', help_text='Portfolio-worthy projects')),
                ('order', models.PositiveIntegerField(default=1)),
                ('estimated_duration', models.CharField(default='4 weeks', help_text='e.g. Weeks 1-4', max_length=100)),
                ('projects_summary', models.TextField(blank=True, default='')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='roadmap.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('topic', 'Core Topic / Concept'), ('practice', 'Hands-on Practice Drill'), ('project', 'Real-world Project / Milestone')], default='topic', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.roadmapstage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
