# Generated by Django 6.1 on 2026-09-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='mentor',
            field=models.CharField(choices=[('odin', 'ODIN - Wise & Strategic (Long-term goals, career planning, leadership)'), ('thor', 'THOR - Motivating & Action-focused (Practical skills, projects, execution)'), ('loki', 'LOKI - Creative & Problem-solving (Creative subjects, innovation, alternatives)'), ('auto', 'Auto-select based on domain')], default='auto', help_text='Your mentor guide for this roadmap', max_length=20),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='mentor_greeting',
            field=models.TextField(blank=True, default='', help_text='Personalized mentor greeting'),
        ),
    ]
